import { pool } from "../config/db.js";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import moment from "moment";

//SUPER USER CHECK
const validateSuperUser = (req, res) => {
  if (req.user.role !== "super_user") {
    res.status(403).json({
      message: "Access denied. Super User only.",
    });
    return false;
  }

  return true;
};

//EXPORT ALL NOTES PDF
export const exportAllNotesPDF = async (
  req,
  res
) => {

  try {

    if (
      !validateSuperUser(
        req,
        res
      )
    )
      return;

    const notes =
      await pool.query(`
        SELECT
          n.*,
          c.full_name,
          c.email,
          c.domain_name,
          u.username
        FROM notes n
        JOIN clients c
          ON n.client_id = c.client_id
        JOIN users u
          ON n.user_id = u.user_id
        ORDER BY n.created_at DESC
      `);

    const totalReplies =
      await pool.query(`
        SELECT COUNT(*)
        FROM replies
      `);

    const doc = new PDFDocument({
  margin: 40,
  size: "A4",
});

res.setHeader("Content-Type", "application/pdf");

res.setHeader(
  "Content-Disposition",
  "attachment; filename=all_notes_report.pdf"
);

doc.pipe(res);

doc
  .fontSize(20)
  .text("Client Notes & Communication Report", {
    align: "center",
  });

doc.moveDown();

doc.fontSize(12);

doc.text(`Generated By: ${req.user.username}`);
doc.text(
  `Generated At: ${moment().format(
    "YYYY-MM-DD HH:mm:ss"
  )}`
);
doc.text(`Total Notes: ${notes.rows.length}`);
doc.text(
  `Total Replies: ${totalReplies.rows[0].count}`
);

doc.moveDown();

notes.rows.forEach((note) => {
  doc
    .fontSize(13)
    .text(`Note #${note.note_id}`, {
      underline: true,
    });

  doc.fontSize(11);

  doc.text(`Client : ${note.full_name}`);
  doc.text(`Type   : ${note.note_type}`);
  doc.text(`User   : ${note.username}`);
  doc.text(
    `Date   : ${moment(note.created_at).format(
      "YYYY-MM-DD HH:mm"
    )}`
  );

  doc.text(`Note:`);

  doc.text(note.note_content);

  doc.moveDown();
});

doc.end();

  } catch (err) {

    console.error(err);

    res.status(500).json({
      message:
        "PDF export failed",
    });

  }

};

//EXPORT CLIENT PDF
export const exportClientNotesPDF =
  async (req, res) => {

    try {

      if (
        !validateSuperUser(
          req,
          res
        )
      )
        return;

      const { clientId } =
        req.params;

      const client =
        await pool.query(
          `
        SELECT *
        FROM clients
        WHERE client_id=$1
      `,
          [clientId]
        );

      const notes =
        await pool.query(
          `
        SELECT
          n.*,
          u.username
        FROM notes n
        JOIN users u
          ON n.user_id=u.user_id
        WHERE n.client_id=$1
        ORDER BY n.created_at DESC
      `,
          [clientId]
        );

      const c = client.rows[0];

const doc = new PDFDocument({
  margin: 40,
  size: "A4",
});

res.setHeader(
  "Content-Type",
  "application/pdf"
);

res.setHeader(
  "Content-Disposition",
  `attachment; filename=client_${clientId}_report.pdf`
);

doc.pipe(res);

doc
  .fontSize(20)
  .text("Client Communication Report", {
    align: "center",
  });

doc.moveDown();

doc.fontSize(12);

doc.text(`Client Name : ${c.full_name}`);
doc.text(`Phone       : ${c.phone_number}`);
doc.text(`Email       : ${c.email}`);
doc.text(`Domain      : ${c.domain_name}`);
doc.text(`WHMCS       : ${c.whmcs_username}`);

doc.moveDown();

for (const note of notes.rows) {

  const replies = await pool.query(
    `
    SELECT
      r.*,
      u.username
    FROM replies r
    JOIN users u
      ON r.user_id=u.user_id
    WHERE r.note_id=$1
    ORDER BY r.created_at ASC
    `,
    [note.note_id]
  );

  doc
    .fontSize(14)
    .text(
      `Note #${note.note_id}`,
      {
        underline: true,
      }
    );

  doc.fontSize(11);

  doc.text(`Type : ${note.note_type}`);
  doc.text(`User : ${note.username}`);

  doc.text(
    `Date : ${moment(
      note.created_at
    ).format(
      "YYYY-MM-DD HH:mm"
    )}`
  );

  doc.moveDown(0.3);

  doc.text(note.note_content);

  doc.moveDown();

  doc.fontSize(12).text("Replies");

  if (replies.rows.length === 0) {

    doc.text("No replies");

  } else {

    replies.rows.forEach((reply) => {

      doc.text(
        `${reply.username}: ${reply.reply_content}`
      );

    });

  }

  doc.moveDown();
}

doc.end();

    } catch (err) {

      console.error(err);

      res.status(500).json({
        message:
          "Client PDF export failed",
      });

    }

  };

//EXPORT ALL NOTES EXCEL
export const exportAllNotesExcel =
  async (req, res) => {

    try {

      if (
        !validateSuperUser(
          req,
          res
        )
      )
        return;

      const workbook =
        new ExcelJS.Workbook();

      const sheet =
        workbook.addWorksheet(
          "All Notes"
        );

      sheet.columns = [
        {
          header:
            "Note ID",
          key: "note_id",
          width: 12,
        },
        {
          header:
            "Client",
          key: "full_name",
          width: 30,
        },
        {
          header:
            "Type",
          key: "note_type",
          width: 20,
        },
        {
          header:
            "User",
          key: "username",
          width: 20,
        },
        {
          header:
            "Date",
          key: "created_at",
          width: 25,
        },
        {
          header:
            "Note",
          key: "note_content",
          width: 60,
        },
      ];

      const notes =
        await pool.query(`
        SELECT
          n.*,
          c.full_name,
          u.username
        FROM notes n
        JOIN clients c
          ON n.client_id=c.client_id
        JOIN users u
          ON n.user_id=u.user_id
        ORDER BY n.created_at DESC
      `);

      notes.rows.forEach(
        (row) =>
          sheet.addRow({
            ...row,
            created_at:
              moment(
                row.created_at
              ).format(
                "YYYY-MM-DD HH:mm"
              ),
          })
      );

      sheet.getRow(
        1
      ).font = {
        bold: true,
      };

      res.setHeader(
        "Content-Type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      );

      res.setHeader(
        "Content-Disposition",
        "attachment; filename=all_notes.xlsx"
      );

      await workbook.xlsx.write(
        res
      );

      res.end();

    } catch (err) {

      console.error(err);

      res.status(500).json({
        message:
          "Excel export failed",
      });

    }

  };

//EXPORT CLIENT EXCEL
export const exportClientNotesExcel =
  async (req, res) => {

    try {

      if (
        !validateSuperUser(
          req,
          res
        )
      )
        return;

      const { clientId } =
        req.params;

      const workbook =
        new ExcelJS.Workbook();

      const sheet =
        workbook.addWorksheet(
          "Client Notes"
        );

      sheet.columns = [
        {
          header:
            "Note ID",
          key: "note_id",
          width: 15,
        },
        {
          header:
            "Type",
          key: "note_type",
          width: 20,
        },
        {
          header:
            "User",
          key: "username",
          width: 20,
        },
        {
          header:
            "Date",
          key: "created_at",
          width: 25,
        },
        {
          header:
            "Note",
          key: "note_content",
          width: 70,
        },
      ];

      const notes =
        await pool.query(
          `
        SELECT
          n.*,
          u.username
        FROM notes n
        JOIN users u
          ON n.user_id=u.user_id
        WHERE n.client_id=$1
        ORDER BY n.created_at DESC
      `,
          [clientId]
        );

      notes.rows.forEach(
        (row) =>
          sheet.addRow({
            ...row,
            created_at:
              moment(
                row.created_at
              ).format(
                "YYYY-MM-DD HH:mm"
              ),
          })
      );

      sheet.getRow(
        1
      ).font = {
        bold: true,
      };

      res.setHeader(
        "Content-Type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
      );

      res.setHeader(
        "Content-Disposition",
        `attachment; filename=client_${clientId}_notes.xlsx`
      );

      await workbook.xlsx.write(
        res
      );

      res.end();

    } catch (err) {

      console.error(err);

      res.status(500).json({
        message:
          "Client Excel export failed",
      });

    }

  };